# Generated by Django 4.2.5 on 2024-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_dealer',
            name='merchant_name',
            field=models.CharField(default='exist', max_length=255),
            preserve_default=False,
        ),
    ]
