# Generated by Django 4.2.5 on 2024-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0002_register_dealer_merchant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_dealer',
            name='merchant_address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
