# Generated by Django 4.2.5 on 2024-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0003_register_dealer_merchant_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_add_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
