# Generated by Django 4.2.5 on 2024-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0004_model_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_add_fields',
            name='timing',
            field=models.TimeField(),
        ),
    ]
