# Generated by Django 4.2.5 on 2024-07-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0005_alter_model_add_fields_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_add_fields',
            old_name='timing',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='model_add_fields',
            name='start_time',
            field=models.TimeField(default='exist'),
            preserve_default=False,
        ),
    ]
