# Generated by Django 4.2.5 on 2024-07-16 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0006_rename_timing_model_add_fields_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_add_fields',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='model_add_fields',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
