# Generated by Django 4.2.5 on 2024-07-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal_app', '0007_alter_model_add_fields_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_add_fields',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='model_add_fields',
            name='start_time',
        ),
    ]
